CLI_PATH="/etc/dijiq/core/cli.py"
CONFIG_ENV="/etc/dijiq/.configs.env"
TELEGRAM_ENV="/etc/dijiq/core/scripts/telegrambot/.env"
ONLINE_API_URL="http://127.0.0.1:25413/online"
LOCALVERSION="/etc/dijiq/VERSION"
LATESTVERSION="https://raw.githubusercontent.com/SeyedHashtag/dijiq/main/VERSION"
LASTESTCHANGE="https://raw.githubusercontent.com/SeyedHashtag/dijiq/main/changelog"